### ISSUE TITLE
Create a MongoDb database for the application

### ISSUE THREAD

**Issue by tusharkini** [tusharkini/WalletBuddy#1]
Create a MongoDB database for the application using the structure given in the JSON file structure. Currently every operation is supported by read and writes from a JSON file that may not be optimal. For better scalability we need to eliminate this part.

**Comment by shlokio** [comment]
Currently upgraded add, addGroup, erase, history and profile functionality to MongoDB.

**Comment by kamathprasad9** [comment]
MongoDB has been integrated into the system is the encounter bugs are now solved
