### ISSUE TITLE
Add extra plotting options

### ISSUE THREAD

**Issue by tusharkini** [tusharkini/WalletBuddy#2]
Currently the system is able to show the bar plot for the expenses incurred by the user. Extend this functionality using matplotlib and add other graphs that might be insightful like pie charts etc.

**Comment by ankurbanerji3** [comment]
I have added extra plots for each type of expense.

**Comment by ankurbanerji3** [comment]
I have added the following for both the kinds of expenditures
1. For individual expenses -- Pie plot and Box plot
2. For group (shared expenses) -- Histogram and Box Plot for a specific category the user chooses 
These have been added in addition to the default bar graphs.
